BEGIN
   FOR r IN (SELECT table_name FROM user_tables WHERE table_name IN ('AUDIT_LOGS', 'TICKETS', 'BOOKINGS', 'SEATS', 'SHOWS', 'VENUES', 'EVENT', 'USERS')) LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || r.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;
END;
/

CREATE TABLE USERS (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    phone VARCHAR2(20),
    password_hash VARCHAR2(255) NOT NULL,
    created_at DATE DEFAULT SYSDATE
);

CREATE TABLE EVENT (
    event_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(200) NOT NULL,
    event_type VARCHAR2(20) CHECK (event_type IN ('MOVIE', 'CONCERT', 'STANDUP', 'SPORT', 'OTHER')),
    duration_minutes NUMBER,
    language VARCHAR2(50),
    description CLOB
);

CREATE TABLE VENUES (
    venue_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_name VARCHAR2(100) NOT NULL,
    location VARCHAR2(200),
    total_capacity NUMBER NOT NULL
);

CREATE TABLE SHOWS (
    show_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id NUMBER NOT NULL REFERENCES EVENT(event_id),
    venue_id NUMBER NOT NULL REFERENCES VENUES(venue_id),
    start_time TIMESTAMP NOT NULL,
    base_price NUMBER(10, 2) NOT NULL
);
CREATE TABLE SEATS (
    seat_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id NUMBER NOT NULL REFERENCES VENUES(venue_id),
    seat_number VARCHAR2(10) NOT NULL,
    row_label CHAR(1) NOT NULL,
    category VARCHAR2(20) CHECK (category IN ('PLATINUM', 'GOLD', 'SILVER')),
    CONSTRAINT UNIQUE_SEAT UNIQUE (venue_id, row_label, seat_number)
);

CREATE TABLE BOOKINGS (
    booking_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL REFERENCES USERS(user_id),
    show_id NUMBER NOT NULL REFERENCES SHOWS(show_id),
    booking_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total_amount NUMBER(10, 2) NOT NULL,
    status VARCHAR2(20) DEFAULT 'CONFIRMED' CHECK (status IN ('CONFIRMED', 'CANCELLED', 'PENDING'))
);

CREATE TABLE TICKETS (
    ticket_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id NUMBER NOT NULL REFERENCES BOOKINGS(booking_id) ON DELETE CASCADE,
    show_id NUMBER NOT NULL REFERENCES SHOWS(show_id),
    seat_id NUMBER NOT NULL REFERENCES SEATS(seat_id),
    actual_price NUMBER(10, 2) NOT NULL,
    CONSTRAINT UNIQUE_SHOW_SEAT UNIQUE (show_id, seat_id)
);

CREATE TABLE AUDIT_LOGS (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR2(30),
    action VARCHAR2(20),
    record_id NUMBER,
    action_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    details VARCHAR2(500)
);
CREATE OR REPLACE VIEW VIEW_ACTIVE_SHOWS AS
SELECT 
    s.show_id,
    e.title,
    e.event_type,
    v.venue_name,
    v.location,
    s.start_time,
    s.base_price
FROM SHOWS s
JOIN EVENT e ON s.event_id = e.event_id
JOIN VENUES v ON s.venue_id = v.venue_id
WHERE s.start_time > CURRENT_TIMESTAMP;

DECLARE
    v_user1 NUMBER; v_user2 NUMBER;
    v_event1 NUMBER; v_event2 NUMBER;
    v_venue1 NUMBER; v_venue2 NUMBER;
    v_show1 NUMBER; v_show2 NUMBER;
BEGIN

    INSERT INTO USERS (name, email, phone, password_hash) VALUES ('John Doe', 'john@example.com', '123', 'pw1') RETURNING user_id INTO v_user1;
    INSERT INTO USERS (name, email, phone, password_hash) VALUES ('Jane Smith', 'jane@example.com', '456', 'pw2') RETURNING user_id INTO v_user2;

    INSERT INTO EVENT (title, event_type, duration_minutes, language) VALUES ('Interstellar', 'MOVIE', 169, 'English') RETURNING event_id INTO v_event1;
    INSERT INTO EVENT (title, event_type, duration_minutes, language) VALUES ('Rock Concert', 'CONCERT', 120, 'English') RETURNING event_id INTO v_event2;

    INSERT INTO VENUES (venue_name, location, total_capacity) VALUES ('Grand Cinema', 'Floor 1', 200) RETURNING venue_id INTO v_venue1;
    INSERT INTO VENUES (venue_name, location, total_capacity) VALUES ('Stadium X', 'Downtown', 50000) RETURNING venue_id INTO v_venue2;

    FOR i IN 1..5 LOOP
        INSERT INTO SEATS (venue_id, seat_number, row_label, category) VALUES (v_venue1, i, 'A', 'GOLD');
    END LOOP;

    INSERT INTO SHOWS (event_id, venue_id, start_time, base_price) 
    VALUES (v_event1, v_venue1, SYSTIMESTAMP + INTERVAL '1' DAY, 15.00) RETURNING show_id INTO v_show1;

    INSERT INTO SHOWS (event_id, venue_id, start_time, base_price) 
    VALUES (v_event2, v_venue2, SYSTIMESTAMP + INTERVAL '7' DAY, 100.00) RETURNING show_id INTO v_show2;

    COMMIT;
END;
/

CREATE OR REPLACE FUNCTION fn_is_seat_available(
    p_show_id IN NUMBER,
    p_seat_id IN NUMBER
) RETURN NUMBER IS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM TICKETS t
    JOIN BOOKINGS b ON t.booking_id = b.booking_id
    WHERE t.show_id = p_show_id 
    AND t.seat_id = p_seat_id
    AND b.status = 'CONFIRMED';
    
    RETURN CASE WHEN v_count = 0 THEN 1 ELSE 0 END;
END;
/

CREATE OR REPLACE PROCEDURE pr_book_ticket(
    p_user_id IN NUMBER,
    p_show_id IN NUMBER,
    p_seat_id IN NUMBER
) IS
    v_base_price NUMBER(10, 2);
    v_booking_id NUMBER;
BEGIN
    IF fn_is_seat_available(p_show_id, p_seat_id) = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Seat is already booked or pending for this show.');
    END IF;

    SELECT base_price INTO v_base_price FROM SHOWS WHERE show_id = p_show_id;

    INSERT INTO BOOKINGS (user_id, show_id, total_amount, status)
    VALUES (p_user_id, p_show_id, v_base_price, 'CONFIRMED')
    RETURNING booking_id INTO v_booking_id;

    INSERT INTO TICKETS (booking_id, show_id, seat_id, actual_price)
    VALUES (v_booking_id, p_show_id, p_seat_id, v_base_price);

    DBMS_OUTPUT.PUT_LINE('Booking created. ID: ' || v_booking_id || '. Please COMMIT to finalize.');

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20002, 'RACE CONDITION DETECTED: This seat was just taken by another user!');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Booking failed: ' || SQLERRM);
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER trg_audit_booking
AFTER INSERT OR UPDATE ON BOOKINGS
FOR EACH ROW
DECLARE
    v_action VARCHAR2(20);
BEGIN
    IF INSERTING THEN
        v_action := 'INSERT';
    ELSE
        v_action := 'UPDATE';
    END IF;

    INSERT INTO AUDIT_LOGS (table_name, action, record_id, details)
    VALUES ('BOOKINGS', 
            v_action, 
            :NEW.booking_id,
            'User: ' || :NEW.user_id || ' | Show: ' || :NEW.show_id || ' | Status: ' || :NEW.status);
END;
/

CREATE OR REPLACE PROCEDURE pr_generate_revenue_report IS
    CURSOR c_revenue IS
        SELECT e.title, NVL(SUM(b.total_amount), 0) as total_revenue, COUNT(b.booking_id) as booking_count
        FROM EVENT e
        JOIN SHOWS s ON e.event_id = s.event_id
        LEFT JOIN BOOKINGS b ON s.show_id = b.show_id AND b.status = 'CONFIRMED'
        GROUP BY e.title;
BEGIN
    DBMS_OUTPUT.PUT_LINE(RPAD('-', 60, '-'));
    DBMS_OUTPUT.PUT_LINE(RPAD('EVENT TITLE', 30) || ' | ' || LPAD('BOOKINGS', 10) || ' | ' || LPAD('REVENUE', 12));
    DBMS_OUTPUT.PUT_LINE(RPAD('-', 60, '-'));
    
    FOR r IN c_revenue LOOP
        DBMS_OUTPUT.PUT_LINE(
            RPAD(r.title, 30) || ' | ' || 
            LPAD(r.booking_count, 10) || ' | ' || 
            LPAD(TO_CHAR(r.total_revenue, '$99,990.99'), 12)
        );
    END LOOP;
    DBMS_OUTPUT.PUT_LINE(RPAD('-', 60, '-'));
END;
/

SET SERVEROUTPUT ON;
DECLARE
    v_uid NUMBER; v_sid NUMBER; v_seat NUMBER;
BEGIN
    SELECT user_id INTO v_uid FROM USERS FETCH FIRST 1 ROW ONLY;
    SELECT show_id INTO v_sid FROM SHOWS FETCH FIRST 1 ROW ONLY;
    SELECT seat_id INTO v_seat FROM SEATS WHERE venue_id = (SELECT venue_id FROM SHOWS WHERE show_id = v_sid) FETCH FIRST 1 ROW ONLY;

    pr_book_ticket(v_uid, v_sid, v_seat);
    COMMIT; 
    pr_generate_revenue_report;
END;
/